- package.json
The real reason for this commit is to publish a new version.
Looks like I don't have all the kinks worked out of this
GitHub/semantic-release workflow. I think the issue is I published a
beta version on the `beta` branch, but when I merged that into `master`
then the tag from `beta` existed on `master` and then there was no
trigger for a new release.
> fix: sort package json

- Dockerfile
Providing more flexibility -- shell can invoke the `monorepo` binary.
This is a breaking change but we won't call it one -- there are no
consumers of this package yet.
Additionally:
- remove the custom `WORKDIR` (default to `/`)
- remove the empty `CMD`
> fix: use sh as docker image entrypoint

- src/make_depend.rs
- templates/makefile
As this may be specified in the monorepo root with a grouped target[^1]
such that `monorepo link` is run even less frequently.
[^1]: https://www.gnu.org/software/make/manual/html_node/Multiple-Targets.html
> fix(make-depend): do not generate link make target

- templates/makefile
as this is not an argument recognized by `touch` in macOS.
> fix: remove --no-touch flag passed to touch

- templates/makefile
Modify the prerequisites list of the target that invokes `monorepo make-depend`
to include the `monorepo` binary directly, rather than the entire node_modules
directly.
This improves resilience in the event that a user interrupts `npm ci` or
`npm install`; these commands will leave behind an incomplete node_modules
directory. If we instead depend on the `monorepo` binary, when GNU make cannot
find that binary it will re-invoke `npm ci` to recover from the inconsistent
node_modules state.
> fix: declare monorepo bin as prereq for generated makefile

- npm/install.js
This commit adds a step to the `npm install` process, that of updating
the downloaded binary's mtime to the current time.
Apparently, the binary created by GitHub Actions retains its original
creation mtime when downloaded by the postinstall script. This interferes
with GNU Make targets that examine the mtime of the `monorepo` binary.
Instead, we accurately reflect the install time in the mtime of the
downloaded binary via the `fs.utimesSync` function offered by Node.js.
> fix: update mtime of downloaded binary after installation

- templates/makefile
Previously, we described that the hard link "target" (the link of the original)
was built by the "source" (the original), which isn't entirely accurate, since
the files are one and the same.
If somehow (not sure how but I'm looking at it) the timestamp of the hard link
"source" is set later than the timestamp of the hard link "source", our current
make target tries to run `ln` again, producing this error
```
ln: failed to create hard link 'packages/my-package/.internal-npm-dependencies/scoped-neat-package-name.tgz': File exists
```
As a fix, we update the make target to specify that the hard link "source" is an
order-only prerequisite, meaning the recipe will only be run if the "source" does
not exist yet. If the timestamp of the "target" is later than the "source", no
action is taken.
As …
> fix(make-depend): use order-only prerequisite for hardlink source

- templates/makefile
This commit adds an order-only prerequisite to the generated
`<package>-docker-dependencies` make target, that of the
`.internal-npm-dependencies` directory.
Currently, the `.internal-npm-dependencies` directory is not created
if there happen to be no use of internal dependencies, which means
the Dockerfile commands
```dockerfile
COPY my-package/.internal-npm-dependencies /tmp/internal-npm-dependencies
```
will not work in all cases (meaning for packages with dependencies and
for those without).
We add the order-only prerequisite so this `.internal-npm-dependencies`
directory is always created, and this `COPY` command will always succeed.
> fix(make-depends): always create internal npm deps directory

- templates/makefile
This flag should fix a race condition we are seeing according to the
error message:
```
npm ERR! File exists: undefined
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
```
> fix: use --force when running `npm pack`

- src/make_depend.rs
Capitalize the first letter of the error messages
> chore: make expect errors consistent

- .github/workflows/release.yml
- .releaserc.json
- bin/monorepo
- npm/binary-install.js
> Verify checksum during post-install hook

- templates/makefile
This commit removes hard-coded use of `lerna bootstrap`'s
`--force-local`[^1] command, so that monorepos that don't want to
opt in to this behavior are not forced to.
For projects that wish to include the `--force-local` flag on every
invocation to `lerna bootstrap`, perhaps to prevent dependency
confusion attacks, we recommend specifying this in the lerna
manifest. For example, your lerna.json could look like
```
{
"packages": [
"packages/*"
],
"command": {
"bootstrap": {
"forceLocal": true
}
}
}
```
To prevent the case where a project was expecting `--force-local`
to be applied, but not specifying this in the configuration file,
we consider this a breaking change.
[^1]: https://github.com/lerna/lerna/blob/main/commands/bootstrap/README.md#--force-local
BREAKING CHANGE: do not specify …
> fix(make-depend)!: remove use of force-local

- .github/workflows/check-licenses.yml
- .github/workflows/check-sources.yml
- deny.toml
Use [cargo-deny] to verify the source location from which dependencies
are obtained, and to restrict the dependencies permitted by license
used.
Looks like there is some overlap in functionality with the cargo-audit
crate, but there are no plans now to remove cargo-audit since the
maintainer-experience of the cron job run in CI is nicer (cargo-audit
will open issues on detected security vulnerabilities).
Closes #53
[cargo-deny]: https://github.com/EmbarkStudios/cargo-deny
> ci: use cargo-deny

- .github/workflows/cargo-deny.yml
- Cargo.toml
for smaller code size. On my x86_64 GNU/Linux maching, the release
binary shrank from 3.7M to 2.1M.
> fix: strip debug symbols from release builds

- .releaserc.json
Previously, prereleases on the beta branch were not "pre-" enough,
meaning releases were published to the `beta` dist-tag but not
marked as pre-release in version number.  This caused the merge of
a prerelease from the beta branch into master to not be re-published
as a full or non-pre release.
The issue is that I overrode the default `branches` semantic-release
setting[^2] that does what I intended with a configuration that
specified that releases from the beta branch should not be treated
as prereleases.
Closes #140
[^2]: https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches
> ci: fix semantic-release prelrease configuration

- src/lerna_manifest.rs
- src/link.rs
- src/package_manifest.rs
Just a bunch of mostly-cosmetic changes.
> Graysons suggestions

- src/lerna_manifest.rs
Stop enforcing that this `version` key exists, since we don't use
it. This should widen the set of `lerna.json` manifests that can be
used as valid inputs to this program.
Additionally, we should expect a small (microseconds or less)
performance improvement since serde is not parsing this field.
> fix: do not require a version key in the lerna manifest

- Cargo.lock
- Cargo.toml
- src/configuration_file.rs
- src/io.rs
- src/lib.rs
- src/link.rs
- src/lint.rs
- src/main.rs
- src/make_depend.rs
- src/monorepo_manifest.rs
- src/opts.rs
- src/package_manifest.rs
- src/pin.rs
- src/query.rs
- src/typescript_config.rs
The `lint-dependency-version` subcommand takes a list of dependencies,
and for each dependency will test that there is at most one version
of that dependency in use throughout the target monorepo.
If this condition is violated, the command will exit non-zero exit code.
The plan is to use this in CI to enforce monorepo invariants for using
only a single version of a given external dependency; for example,
`typescript`.
Ideally we separate out the library and binary code in this crate,
and later we can write multiple binaries that use this library, one
of which will invoke this new code and can function as a stand-alone
Drone plugin. Thinking about it now, the coupling to Drone is not a
goal of this crate but importing the library portion of this codebase
from a different crate will be a …
> feat: add subcommand to lint depenendency versions for consistent values

- README.md
This prevents CI failures on PRs to display "CI: failing" on the
readme.
> docs: always display build status from master branch

- Cargo.lock
- Cargo.toml
- src/configuration_file.rs
- src/io.rs
- src/link.rs
- src/lint.rs
- src/monorepo_manifest.rs
- src/package_manifest.rs
- src/pin.rs
- src/query.rs
- src/typescript_config.rs
This commit improves error messages presented to the user when encountering errors parsing JSON.
This required a bit of refactoring, since we were performing too much work up-front, and swallowing the helpful errors with a fallback (that stops looking for a lerna manifest and starts looking for an npm 7 workspace) that happened too late.
I took this opportunity to improve the representation of package.json manifests, which makes interaction with serde more ergonomic.
Here's an example of an error message when I remove the `version` property in a package.json file:
```
; monorepo pin --check
Error: Unexpected contents in "./packages/my-package/package.json"
I'm trying to parse the following properties and values out
of this package.json file:
- name: string
- version: string
and if the any …
```
> fix: improve error messages presented to the user

- .github/workflows/ci.yml
- .github/workflows/release.yml
Ticket: concurrency-throttle-on-gha-workflows
> ci: use concurrency limits to prevent release issues

- .github/workflows/release.yml
- .gitignore
- .releaserc.json
- Cargo.toml
- Dockerfile
- flake.nix
- package-lock.json
- package.json
- src/lib.rs
- src/monorepo_manifest.rs
This requires exposing a few more modules.
> Split crate into a library and a binary
